// Generated by scripts/holo-theme.mjs from the tokens (holocore-ui/tokens). Do not edit.
export const HOLO = Object.freeze({"core":"#14A0E6","rim":"#5CC8FF","accent":"#DD5A1E","glow":"#E8F4FB","ground":"#030B14"} as const);
