// Writes packages/holocore/src/theme-values.ts from the package's own tokens,
// so the Holo preset carries the token values with no runtime dependency on
// the tokens package.
//   node scripts/holo-theme.mjs           write the file
//   node scripts/holo-theme.mjs --check   exit 1 when the committed file differs
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { TOKENS } from "../packages/holocore/tokens/src/index.mjs";

const target = fileURLToPath(new URL("../packages/holocore/src/theme-values.ts", import.meta.url));

export function renderThemeValues() {
  const c = TOKENS.jarvis.color;
  const holo = { core: c.p, rim: c.p2, accent: c.acc, glow: c.text, ground: c.ground };
  return [
    "// Generated by scripts/holo-theme.mjs from the tokens (holocore-ui/tokens). Do not edit.",
    `export const HOLO = Object.freeze(${JSON.stringify(holo)} as const);`,
    "",
  ].join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const next = renderThemeValues();
  if (process.argv.includes("--check")) {
    let now = "";
    try { now = readFileSync(target, "utf8").replace(/\r\n/g, "\n"); } catch {}
    if (now !== next) { console.error("packages/holocore/src/theme-values.ts is out of date: run node scripts/holo-theme.mjs"); process.exit(1); }
  } else {
    writeFileSync(target, next);
    console.log("wrote packages/holocore/src/theme-values.ts");
  }
}
