// Generates tokens/css/*.css from tokens/src/tokens.mjs. Run after changing a value:
//   npm run tokens -w holocore-ui
// --check exits 1 when a committed file differs from what the source generates.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { TOKENS } from "../tokens/src/tokens.mjs";

const HEADER = "/* Generated by holocore-ui/tokens from tokens/src/tokens.mjs. Do not edit. */\n";
// CSS weight names, so a CSS-only adopter reads --weight-display-bold rather than a bare number.
const WEIGHT_NAMES = { 100: "thin", 200: "extralight", 300: "light", 400: "regular", 500: "medium", 600: "semibold", 700: "bold", 800: "extrabold", 900: "black" };
const weightName = (w) => {
  if (!WEIGHT_NAMES[w]) throw new Error(`weight ${w} has no CSS name: use a multiple of 100 from 100 to 900`);
  return WEIGHT_NAMES[w];
};
const family = (f) => (["serif", "sans-serif", "monospace", "system-ui", "ui-monospace"].includes(f) ? f : `'${f}'`);

export function renderCss(name, selector) {
  const b = TOKENS[name];
  const lines = [];
  for (const [k, v] of Object.entries(b.color)) lines.push(`--${k}: ${v};`);
  for (const [k, v] of Object.entries(b.font)) lines.push(`--font-${k}: ${v.map(family).join(", ")};`);
  for (const [k, ws] of Object.entries(b.weight)) for (const w of ws) lines.push(`--weight-${k}-${weightName(w)}: ${w};`);
  for (const [k, v] of Object.entries(b.size)) lines.push(`--size-${k}: ${v}px;`);
  b.space.forEach((v) => lines.push(`--s-${v / 4}: ${v}px;`));
  for (const [k, v] of Object.entries(b.radius)) lines.push(`--r-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(b.shadow)) lines.push(`--shadow-${k}: ${v};`);
  return `${selector} {\n${lines.map((l) => `  ${l}`).join("\n")}\n}\n`;
}

export function renderAll() {
  return {
    "antonio-molina.css": HEADER + renderCss("antonio-molina", ":root"),
    "jarvis.css": HEADER + renderCss("jarvis", ":root"),
    "tokens.css": HEADER + Object.keys(TOKENS).map((n) => renderCss(n, `[data-brand="${n}"]`)).join("\n"),
  };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  let drift = false;
  for (const [file, css] of Object.entries(renderAll())) {
    const path = fileURLToPath(new URL(`../tokens/css/${file}`, import.meta.url));
    if (check) {
      let now = "";
      try { now = readFileSync(path, "utf8"); } catch {}
      if (now !== css) { console.error(`css/${file} is out of date`); drift = true; }
    } else {
      writeFileSync(path, css);
      console.log(`wrote css/${file}`);
    }
  }
  if (drift) process.exit(1);
}
