import { readFileSync } from "node:fs";
import { expect, test } from "vitest";
import { renderAll, renderCss } from "../../scripts/tokens-build.mjs";
import { TOKENS } from "../../tokens/src/tokens.mjs";

const here = (p) => new URL(`../../tokens/${p}`, import.meta.url);

test("the committed css is exactly what the source generates", () => {
  for (const [file, css] of Object.entries(renderAll())) {
    expect(readFileSync(here(`css/${file}`), "utf8"), `${file}: run npm run tokens -w holocore-ui`).toBe(css);
  }
});

test("a brand renders its roles, fonts and scales", () => {
  const css = renderCss("antonio-molina", ":root");
  expect(css).toContain("--navy: #16283F;");
  expect(css).toContain("--orange-text: #B4471A;");
  expect(css).toContain("--font-display: 'Bricolage Grotesque', 'Inter', 'Noto Sans Thai', 'Segoe UI', sans-serif;");
  expect(css).toContain("--s-1: 4px;");
  expect(css).toContain("--r-lg: 16px;");
  expect(css).toContain("--size-body: 17px;");
});

test("tokens.css scopes each brand under data-brand", () => {
  const css = renderAll()["tokens.css"];
  expect(css).toContain('[data-brand="antonio-molina"] {');
  expect(css).toContain('[data-brand="jarvis"] {');
});

test("generated files say they are generated", () => {
  for (const css of Object.values(renderAll())) expect(css.startsWith("/* Generated by holocore-ui/tokens")).toBe(true);
});

// From review: CSS-only adopters had no way to get the approved weights.
test("weights are emitted as named custom properties, per role", () => {
  const am = renderCss("antonio-molina", ":root");
  expect(am).toContain("--weight-display-semibold: 600;");
  expect(am).toContain("--weight-display-bold: 700;");
  expect(am).toContain("--weight-display-extrabold: 800;");
  expect(am).toContain("--weight-body-regular: 400;");
  expect(am).toContain("--weight-body-bold: 700;");
  expect(renderCss("jarvis", ":root")).toContain("--weight-mono-medium: 500;");
});

test("every weight of every brand is emitted, and nothing else under --weight-", () => {
  for (const [name, b] of Object.entries(TOKENS)) {
    const emitted = [...renderCss(name, ":root").matchAll(/--weight-([a-z]+)-[a-z]+: (\d+);/g)].map((m) => `${m[1]}:${m[2]}`).sort();
    const expected = Object.entries(b.weight).flatMap(([role, ws]) => ws.map((w) => `${role}:${w}`)).sort();
    expect(emitted, name).toEqual(expected);
  }
});
